config/routes.rb
Rails.application.routes.draw do
  resources :cities
  get 'home/index'
  get 'admin/index'

  root 'drivers#new'

  devise_for :users
  resources :consts
  resources :fuels
  resources :rents
  resources :drivers
end

app/models/const.rb
class Const < ApplicationRecord
  has_many :drivers
end

app/controllers/consts_controller.rb
class ConstsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_const, only: [:show, :edit, :update, :destroy]

  def index
    @consts = Const.all
  end

  def show
    @total_com_seguro = (@const.ipva_dpvat_licenciamento.to_f + @const.manutencao.to_f + @const.depreciacao.to_f + @const.seguro.to_f)/12
    @total_sem_seguro = (@const.ipva_dpvat_licenciamento.to_f + @const.manutencao.to_f + @const.depreciacao.to_f)/12

  end

  def new
    @const = Const.new
  end

  def edit
  end

  def create
    @const = Const.new(const_params)

    respond_to do |format|
      if @const.save
        format.html { redirect_to @const, notice: 'criado.' }
        format.json { render :show, status: :created, location: @const }
      else
        format.html { render :new }
        format.json { render json: @const.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @const.update(const_params)
        format.html { redirect_to @const, notice: 'atualizado.' }
        format.json { render :show, status: :ok, location: @const }
      else
        format.html { render :edit }
        format.json { render json: @const.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @const.destroy
    respond_to do |format|
      format.html { redirect_to consts_url, notice: 'excluído.' }
      format.json { head :no_content }
    end
  end

  private
    def set_const
      @const = Const.find(params[:id])
    end

    def const_params
      params.require(:const).permit(:ipva_dpvat_licenciamento, :manutencao, :depreciacao, :seguro, :total, :mensal)
    end
end

app/helpers/consts_helper.rb
module ConstsHelper
end

app/views/consts/_form.html.erb
<%= form_with(model: const, local: true) do |form| %>
  <% if const.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(const.errors.count, "error") %> prohibited this const from being saved:</h2>

      <ul>
      <% const.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ipva_dpvat_licenciamento, "Ipva/Dpvat/Licenciamento" %>
    <%= form.text_field :ipva_dpvat_licenciamento %>
  </div>

  <div class="field">
    <%= form.label :manutencao, "Manutenção" %>
    <%= form.text_field :manutencao %>
  </div>

  <div class="field">
    <%= form.label :depreciacao, "Depreciação" %>
    <%= form.text_field :depreciacao %>
  </div>

  <div class="field">
    <%= form.label :seguro, "Seguro" %>
    <%= form.text_field :seguro %>
  </div>

  <div class="actions">
    <%= form.submit t('utils.save'), :class => "btn btn-save" %>
  </div>
<% end %>

app/views/consts/edit.html.erb
<%= render "admin/header" %>

<div class="content">
  <h1><%=t('utils.editing')%> <%=t('utils.const')%></h1>

  <%= render 'form', const: @const %>

  <%= link_to t('utils.back'), consts_path, :class => "btn btn-back" %>
</div>

app/views/consts/index.html.erb
<%= render "admin/header" %>

<div class="content">
  <p id="notice"><%= notice %></p>

  <h1><%=t('utils.consts')%></h1>


  <% @consts.each do |const| %>
    <p>
      <strong>Ipva/Dpvat/Licenciamento:</strong>
      <span>R$</span><%= const.ipva_dpvat_licenciamento %>
    </p>

    <p>
      <strong>Manutencao:</strong>
      <span>R$</span><%= const.manutencao %>
    </p>

    <p>
      <strong>Depreciacao:</strong>
      <span>R$</span><%= const.depreciacao %>
    </p>

    <p>
      <strong>Seguro:</strong>
      <span>R$</span><%= const.seguro %>
    </p>

    <div class="button-box">
      <p><%= link_to t('utils.edit'), edit_const_path(const), :class => "btn btn-edit" %></p>
    </div>

  <% end %>
</div>

app/views/consts/new.html.erb
<%= render "admin/header" %>

<div class="content">
  <h1><%=t('utils.new')%> <%=t('utils.const')%></h1>

  <%= render 'form', const: @const %>

  <%= link_to t('utils.back'), consts_path, :class => "btn btn-back"  %>
</div>

app/views/consts/show.html.erb
<%= render "admin/header" %>

<div class="content">
  <p id="notice"><%= notice %></p>

  <h1><%=t('utils.const')%></h1>

  <p>
    <strong>Ipva/Dpvat/Licenciamento:</strong>
    <%= @const.ipva_dpvat_licenciamento %>
  </p>

  <p>
    <strong>Manutenção:</strong>
    <%= @const.manutencao %>
  </p>

  <p>
    <strong>Depreciacao:</strong>
    <%= @const.depreciacao %>
  </p>

  <p>
    <strong>Seguro:</strong>
    <%= @const.seguro %>
  </p>

  <p>
    <strong>Total com seguro:</strong>
    <span>R$</span><%= @total_com_seguro %>
  </p>

  <p>
    <strong>Total sem seguro:</strong>
    <span>R$</span><%= @total_sem_seguro %>
  </p>

  <%= link_to t('utils.edit'), edit_const_path(@const), :class => "btn btn-edit"  %>
  <%= link_to t('utils.back'), consts_path, :class => "btn btn-back"  %>
</div>