config/routes.rb
Rails.application.routes.draw do
  resources :cities
  get 'home/index'
  get 'admin/index'

  root 'drivers#new'

  devise_for :users
  resources :consts
  resources :fuels
  resources :rents
  resources :drivers
end

app/models/rent.rb
class Rent < ApplicationRecord
  has_many :drivers
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rent, only: [:show, :edit, :update, :destroy]

  def index
    @rents = Rent.all
  end

  def show
  end

  def new
    @rent = Rent.new
  end

  def edit
  end

  def create
    @rent = Rent.new(rent_params)

    respond_to do |format|
      if @rent.save
        format.html { redirect_to @rent, notice: 'criado.' }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to @rent, notice: 'atualizado.' }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rent.destroy
    respond_to do |format|
      format.html { redirect_to rents_url, notice: 'excluído.' }
      format.json { head :no_content }
    end
  end

  private
    def set_rent
      @rent = Rent.find(params[:id])
    end

    def rent_params
      params.require(:rent).permit(:nome, :valor)
    end
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_form.html.erb
<%= form_with(model: rent, local: true) do |form| %>
  <% if rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="actions">
    <%= form.submit t('utils.save'), :class => "btn btn-save" %>
  </div>
<% end %>

app/views/rents/edit.html.erb
<%= render "admin/header" %>

<div class="content">
  <h1>Editing Rent</h1>

  <%= render 'form', rent: @rent %>

  <%= link_to t('utils.back'), rents_path, :class => "btn btn-back" %>
</div>

app/views/rents/index.html.erb
<%= render "admin/header" %>

<div class="content">
  <p id="notice"><%= notice %></p>

  <h1><%=t('utils.rent')%></h1>
  <% @rents.each do |rent| %>
    <p>
      <strong>Nome:</strong>
      <%= rent.nome %>
    </p>

    <p>
      <strong>Valor:</strong>
      <%= rent.valor %>
    </p>

    <div class="button-box">
      <p><%= link_to t('utils.edit'), edit_rent_path(rent), :class => "btn btn-edit" %></p>
    </div>
  <% end %>
</div>

app/views/rents/new.html.erb
<%= render "admin/header" %>

<div class="content">
  <h1><%=t('utils.new')%> <%=t('utils.rent')%></h1>

  <%= render 'form', rent: @rent %>

  <%= link_to t('utils.back'), rents_path, :class => "btn btn-back" %>  
</div>

app/views/rents/show.html.erb
<%= render "admin/header" %>

<div class="content">
  <p id="notice"><%= notice %></p>

  <h1><%=t('utils.rent')%></h1>

  <p>
    <strong>Nome:</strong>
    <%= @rent.nome %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= @rent.valor %>
  </p>

  <%= link_to t('utils.edit'), edit_rent_path(@rent), :class => "btn btn-edit" %>
  <%= link_to t('utils.back'), rents_path, :class => "btn btn-back" %>  
</div>