config/routes.rb
Rails.application.routes.draw do
  resources :cities
  get 'home/index'
  get 'admin/index'

  root 'drivers#new'

  devise_for :users
  resources :consts
  resources :fuels
  resources :rents
  resources :drivers
end

app/models/city.rb
class City < ApplicationRecord
  has_many :drivers
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.all
  end

  def show
  end

  def new
    @city = City.new
  end

  def edit
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'criado.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'atualizado.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'excluído.' }
      format.json { head :no_content }
    end
  end

  private
    def set_city
      @city = City.find(params[:id])
    end

    def city_params
      params.require(:city).permit(:name, :taxa_99, :tph, :tarifa_base, :rs_km, :rs_min, :tarifa_minima, :tempo_medio_corrida, :distancia_pax, :distancia_corrida, :asp)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nome"%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :taxa_99 %>
    <%= form.text_field :taxa_99 %>
  </div>

  <div class="field">
    <%= form.label :tph %>
    <%= form.text_field :tph %>
  </div>

  <div class="field">
    <%= form.label :tarifa_base %>
    <%= form.text_field :tarifa_base %>
  </div>

  <div class="field">
    <%= form.label :rs_km %>
    <%= form.text_field :rs_km %>
  </div>

  <div class="field">
    <%= form.label :rs_min %>
    <%= form.text_field :rs_min %>
  </div>

  <div class="field">
    <%= form.label :tarifa_minima %>
    <%= form.text_field :tarifa_minima %>
  </div>

  <div class="field">
    <%= form.label :tempo_medio_corrida %>
    <%= form.text_field :tempo_medio_corrida %>
  </div>

  <div class="field">
    <%= form.label :distancia_pax %>
    <%= form.text_field :distancia_pax %>
  </div>

  <div class="field">
    <%= form.label :distancia_corrida %>
    <%= form.text_field :distancia_corrida %>
  </div>

  <div class="field">
    <%= form.label :asp %>
    <%= form.text_field :asp %>
  </div>

  <div class="actions">
    <%= form.submit t('utils.save'), :class => "btn btn-save"  %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<%= render "admin/header" %>

<div class="content">
  <h1><%=t('utils.editing')%> <%=t('utils.city')%></h1>

  <%= render 'form', city: @city %>

  <%= link_to t('utils.back'), cities_path, :class => "btn btn-back"%>
</div>

app/views/cities/index.html.erb
<%= render "admin/header" %>

<div class="content">
  <p id="notice"><%= notice %></p>

  <h1><%=t('utils.cities')%></h1>
    <% @cities.each do |city| %>
      <p>
        <strong>Name:</strong>
        <%= city.name %>
      </p>

      <p>
        <strong>Taxa 99:</strong>
        <%= city.taxa_99 %>
      </p>

      <p>
        <strong>Tph:</strong>
        <%= city.tph %>
      </p>

      <p>
        <strong>Tarifa base:</strong>
        <%= city.tarifa_base %>
      </p>

      <p>
        <strong>Rs km:</strong>
        <%= city.rs_km %>
      </p>

      <p>
        <strong>Rs min:</strong>
        <%= city.rs_min %>
      </p>

      <p>
        <strong>Tarifa minima:</strong>
        <%= city.tarifa_minima %>
      </p>

      <p>
        <strong>Tempo medio corrida:</strong>
        <%= city.tempo_medio_corrida %>
      </p>

      <p>
        <strong>Distancia pax:</strong>
        <%= city.distancia_pax %>
      </p>

      <p>
        <strong>Distancia corrida:</strong>
        <%= city.distancia_corrida %>
      </p>

      <p>
        <strong>Asp:</strong>
        <%= city.asp %>
      </p>

      <div class="button-box">
        <p><%= link_to t('utils.show'), city, :class => "btn btn-show"%></p>
        <p><%= link_to t('utils.edit'), edit_city_path(city), :class => "btn btn-edit"%></p>
        <p><%= link_to t('utils.destroy'), city, method: :delete, data: { confirm: 'Você tem certeza?' }, :class => "btn btn-delete" %></p>
      </div>

      <hr>
    <% end %>

  <%= link_to t('utils.new'), new_city_path, :class => "btn btn-new" %>
</div>

app/views/cities/new.html.erb
<%= render "admin/header" %>

<div class="content">
  <h1><%=t('utils.new2')%> <%=t('utils.city')%></h1>

  <%= render 'form', city: @city %>

  <%= link_to t('utils.back'), cities_path, :class => "btn btn-back"%>
</div>

app/views/cities/show.html.erb
<%= render "admin/header" %>

<div class="content">
  <p id="notice"><%= notice %></p>

  <h1><%=t('utils.cities')%></h1>

  <p>
    <strong>Name:</strong>
    <%= @city.name %>
  </p>

  <p>
    <strong>Taxa 99:</strong>
    <%= @city.taxa_99 %>
  </p>

  <p>
    <strong>Tph:</strong>
    <%= @city.tph %>
  </p>

  <p>
    <strong>Tarifa base:</strong>
    <%= @city.tarifa_base %>
  </p>

  <p>
    <strong>Rs km:</strong>
    <%= @city.rs_km %>
  </p>

  <p>
    <strong>Rs min:</strong>
    <%= @city.rs_min %>
  </p>

  <p>
    <strong>Tarifa minima:</strong>
    <%= @city.tarifa_minima %>
  </p>

  <p>
    <strong>Tempo medio corrida:</strong>
    <%= @city.tempo_medio_corrida %>
  </p>

  <p>
    <strong>Distancia pax:</strong>
    <%= @city.distancia_pax %>
  </p>

  <p>
    <strong>Distancia corrida:</strong>
    <%= @city.distancia_corrida %>
  </p>

  <p>
    <strong>Asp:</strong>
    <%= @city.asp %>
  </p>

  <%= link_to t('utils.edit'), edit_city_path(@city), :class => "btn btn-edit" %>
  <%= link_to t('utils.back'), cities_path, :class => "btn btn-back" %>  
</div>