config/routes.rb
Rails.application.routes.draw do
  resources :cities
  get 'home/index'
  get 'admin/index'

  root 'drivers#new'

  devise_for :users
  resources :consts
  resources :fuels
  resources :rents
  resources :drivers
end

app/models/fuel.rb
class Fuel < ApplicationRecord
  has_many :drivers
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_fuel, only: [:show, :edit, :update, :destroy]

  def index
    @fuels = Fuel.all
  end

  def show
  end

  def new
    @fuel = Fuel.new
  end

  def edit
  end

  def create
    @fuel = Fuel.new(fuel_params)

    respond_to do |format|
      if @fuel.save
        format.html { redirect_to @fuel, notice: 'criado.' }
        format.json { render :show, status: :created, location: @fuel }
      else
        format.html { render :new }
        format.json { render json: @fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuels/1
  # PATCH/PUT /fuels/1.json
  def update
    respond_to do |format|
      if @fuel.update(fuel_params)
        format.html { redirect_to @fuel, notice: 'atualizado.' }
        format.json { render :show, status: :ok, location: @fuel }
      else
        format.html { render :edit }
        format.json { render json: @fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fuel.destroy
    respond_to do |format|
      format.html { redirect_to fuels_url, notice: 'excluído.' }
      format.json { head :no_content }
    end
  end

  private
    def set_fuel
      @fuel = Fuel.find(params[:id])
    end

    def fuel_params
      params.require(:fuel).permit(:nome, :valor, :tipo)
    end
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/views/fuels/_form.html.erb
<%= form_with(model: fuel, local: true) do |form| %>
  <% if fuel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fuel.errors.count, "error") %> prohibited this fuel from being saved:</h2>

      <ul>
      <% fuel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="actions">
    <%= form.submit t('utils.save'), :class => "btn btn-save" %>
  </div>
<% end %>

app/views/fuels/edit.html.erb
<%= render "admin/header" %>

<div class="content">
  <h1><%=t('utils.editing')%> <%=t('utils.fuel')%></h1>

  <%= render 'form', fuel: @fuel %>

  <%= link_to t('utils.back'), fuels_path, :class => "btn btn-back" %>
</div>

app/views/fuels/index.html.erb
<%= render "admin/header" %>

<div class="content">
  <p id="notice"><%= notice %></p>

  <h1><%=t('utils.fuels')%></h1>


  <% @fuels.each do |fuel| %>
    <p>
      <strong>Nome:</strong>
      <%= fuel.nome %>
    </p>

    <p>
      <strong>Valor:</strong>
      <%= fuel.valor %><%= fuel.tipo %>
    </p>

    <div class="button-box">
      <p><%= link_to t('utils.show'), fuel, :class => "btn btn-show"  %></p>

      <p><%= link_to t('utils.edit'), edit_fuel_path(fuel), :class => "btn btn-edit"  %></p>

    </div>
  <% end %>


  <%= link_to t('utils.new'), new_fuel_path, :class => "btn btn-new" %>
</div>

app/views/fuels/new.html.erb
<%= render "admin/header" %>

<div class="content">
  <h1><%=t('utils.new')%> <%=t('utils.fuel')%></h1>

  <%= render 'form', fuel: @fuel %>

  <%= link_to t('utils.back'), fuels_path, :class => "btn btn-back" %>
</div>

app/views/fuels/show.html.erb
<%= render "admin/header" %>

<div class="content">
  <p id="notice"><%= notice %></p>

  <h1><%=t('utils.fuel')%></h1>

  <p>
    <strong>Nome:</strong>
    <%= @fuel.nome %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= @fuel.valor %><%= @fuel.tipo %>
  </p>

  <%= link_to t('utils.edit'), edit_fuel_path(@fuel), :class => "btn btn-edit" %>
  <%= link_to t('utils.back'), fuels_path, :class => "btn btn-back" %>
</div>